# NUMPY BASICS

### Kreowanie array

In [50]:
import numpy as np

a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]])

### Initial Placeholders

In [ ]:
np.zeros((3,4))                 #Create an array of zeros
np.ones((2,3,4),dtype=np.int16) # Create an array of ones


np.arange(10,25,5) # Create an array of evenly spaced values (step value)
np.linspace(0,2,9) # Create an array of evenly spaced values (number of samples)
np.full((2,2),7)   # Create a constant array
np.eye(2)          # Create a 2X2 identity matrix
np.empty((3,2))    #Create an empty array
np.identity()

### I/O

In [ ]:
np.save('my_array', a)
np.savez('array.npz', a, b)
np.load('my_array.npy')

np.loadtxt("myfile.txt")                    # TEKST
np.genfromtxt("my_file.csv", delimiter=',') # TEKST
np.savetxt("myarray.txt", a, delimiter=" ") # TEKST

### Inspecting Your Array

In [ ]:
a.shape              # Array dimensions
len(a)              # Length of array
b.ndim              # Number of array dimensions
e.size              # Number of array elements
b.dtype             # Data type of array elements
b.dtype.name        # Name of data type
b.astype(int)       # Convert an array to a different typ   

### Copying Arrays

In [ ]:
h = a.view()   # Create a view of the array with the same data
np.copy(a)     # Create a copy of the array
h = a.copy())  # Create a deep copy of the array

### Sorting Arrays

In [ ]:
a.sort()       # Sort an array
c.sort(axis=0) # Sort the elements of an array's axis

### Arithmetic Operations

In [ ]:
np.subtract(a,b) # Odejmowanie
np.add(b,a)      # Dodawanie
np.divide(a,b)   # Dzielenie
np.sqrt(b)       # Kwadrat ?????????
np.sin(a)        # Sinus
np.cos(b)        # Cosinus

### Subsetting, Slicing, Indexing

##### Subsetting

In [ ]:
a[2]          # Select the element at the 2nd index
b[1,2]        # Select the element at row 0 column 2 (equivalent to b[1][2] )

##### Slicing

In [ ]:
a[0:2]        # Select items at index 0 and 1
b[0:2,1]      # Select items at rows 0 and 1 in column 1
b[:1]         # Select all items at row 0 (equivalent to b[0:1, :] )
c[1,...]      # Same as [1,:,:]
a[ : :-1]     # Reversed array a

##### Indexing (boolean/fancy)

In [ ]:
# Boolean Indexing
a[a<2]        # Select elements from a less than 2

# Fancy Indexing
b[[1, 0, 1, 0],[0, 1, 2, 0]] # Select elements (1,0) , (0,1) , (1,2) and (0,0)
b[[1, 0, 1, 0]][:,[0,1,2,0]] # Select a subset of the matrix’s rows and columns

### Array Manipulation

###### Transposing Array

In [ ]:
i = np.transpose(b)  # Permute array dimensions
i.T                  # Permute array dimensions

###### Changing Array Shape

In [ ]:
b.ravel()           # Flatten the array
g.reshape(3,-2) # Reshape, but don’t change data

###### Adding/Removing Elements

In [ ]:
h.resize((2,6))     # Return a new array with shape (2,6)
np.append(h,g)      # Append items to an array
np.insert(a, 1, 5)  # Insert items in an array
np.delete(a,[1])    # Delete items from an array

###### Combining Arrays

In [ ]:
np.concatenate((a,d),axis=0) # Concatenate arrays
np.vstack((a,b))             # Stack arrays vertically (row-wise)
np.r_[e,f]                   # Stack arrays vertically (row-wise)
np.hstack((e,f))             # Stack arrays horizontally (column-wise)
np.column_stack((a,d))       # Create stacked column-wise arrays
np.c_[a,d]                   # Create stacked column-wise arrays

###### Splitting Arrays

In [ ]:
np.hsplit(a,3)   # Split the array horizontally at the 3rd index
np.vsplit(c,2)   # Split the array vertically at the 2nd index

In [5]:
import numpy as np

# Glossary

Podstawowe numpaje w kursie Andrew NG

######  np.exp
######  np.array
######  np.shape
######  np.reshape
######  np.linalg.norm(x, ord=int,axis=int,keepdims=bool)
######  np.sum(value, axis=int, keepdims=bool)
######  np.zeros(x,y)
######  np.dot(x,y)
######  np.outer(x,y)
######  np.multiply(x,y)
######  np.random.rand(x,y)
######  np.absolute()
######  np.squeeze
######  np.log()
######  np.mean()
######  np.tanh()
######  np.round()
######  np.random.seed()
######  np.random.randn 
######  import time
######  time.process_time()

###  1.1-2 NP EXP
### - np.array
### - np.exp 

In [17]:

import numpy as np

# example of np.exp
x = np.array([1, 2, 3])

print("EXAMPLE OF np.exp")
print("(basicly x * 2.718 for all values in x)")
print("")
print(np.exp(x)) # result is (exp(1), exp(2), exp(3))
print("")



#example of vector operation
x = np.array([1, 2, 3])

print("example of vector operation on x + 3")
print(x + 3)

EXAMPLE OF np.exp
(basicly x * 2.718 for all values in x)

[  2.71828183   7.3890561   20.08553692]

example of vector operation on x + 3
[4 5 6]


In [69]:
import numpy as np

def sigmoid(x):
    s = 1 / (1 + np.exp(-x))
    
    return s

x = np.array([1, 2, 3])
sigmoid(x)

array([ 0.73105858,  0.88079708,  0.95257413])

In [70]:
def sigmoid_derivative(x):
    """
    Compute the gradient (also called the slope or derivative) of the sigmoid function with respect to its input x.
    You can store the output of the sigmoid function into variables and then use it to calculate the gradient.
    
    Arguments:
    x -- A scalar or numpy array

    Return:
    ds -- Your computed gradient.
    """
    s = 1 / (1 + np.exp(-x))
    ds = s*(1-s)
    return ds

x = np.array([1, 2, 3])
print ("sigmoid_derivative(x) = " + str(sigmoid_derivative(x)))


sigmoid_derivative(x) = [ 0.19661193  0.10499359  0.04517666]


### 1.3 Reshaping arrays
### - np.shape
### - np.reshape

In [71]:
# GRADED FUNCTION: image2vector
def image2vector(image):
    """
    Argument:
    image -- a numpy array of shape (length, height, depth)
    Returns:
    v -- a vector of shape (length*height*depth, 1)
    """
    print(image)
    v = image.reshape((image.shape[0] * image.shape[1], image.shape[2]))
    print(v)
    return v


# This is a 3 by 3 by 2 array, typically images will be (num_px_x, num_px_y,3) where 3 represents the RGB values
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

print ("image2vector(image) = " + str(image2vector(image)))


[[[ 0.67826139  0.29380381]
  [ 0.90714982  0.52835647]
  [ 0.4215251   0.45017551]]

 [[ 0.92814219  0.96677647]
  [ 0.85304703  0.52351845]
  [ 0.19981397  0.27417313]]

 [[ 0.60659855  0.00533165]
  [ 0.10820313  0.49978937]
  [ 0.34144279  0.94630077]]]
[[ 0.67826139  0.29380381]
 [ 0.90714982  0.52835647]
 [ 0.4215251   0.45017551]
 [ 0.92814219  0.96677647]
 [ 0.85304703  0.52351845]
 [ 0.19981397  0.27417313]
 [ 0.60659855  0.00533165]
 [ 0.10820313  0.49978937]
 [ 0.34144279  0.94630077]]
image2vector(image) = [[ 0.67826139  0.29380381]
 [ 0.90714982  0.52835647]
 [ 0.4215251   0.45017551]
 [ 0.92814219  0.96677647]
 [ 0.85304703  0.52351845]
 [ 0.19981397  0.27417313]
 [ 0.60659855  0.00533165]
 [ 0.10820313  0.49978937]
 [ 0.34144279  0.94630077]]


### 1.4 - Normalizing rows
### - np.linalg.norm(x, ord=int,axis=int,keepdims=bool)

In [129]:
# GRADED FUNCTION: normalizeRows

def normalizeRows(x):
    """
    Function normalizes each row of the matrix x (to have unit length).
    Argument:   x -- A numpy matrix of shape (n, m)
    Returns:    x -- The normalized (by row) numpy matrix. You are allowed to modify x.
    """
    
    x_norm = np.linalg.norm(x, ord = 2, axis = 1, keepdims = True)
    x = x / x_norm
    print("")
    print("X NORM")
    print(x_norm)
    print("")
    print("X/X_NORM")
    return x

x = np.array([
    [0, 2, 0, 0],
    [1, 4, 2, 2]])

# normalizeRows(x) to use #





print("not normalized Rows")
print(str(x))
print(" ")
print("normalized Rows")
print(str(normalizeRows(x)))

not normalized Rows
[[0 2 0 0]
 [1 4 2 2]]
 
normalized Rows

X NORM
[[ 2.]
 [ 5.]]

X/X_NORM
[[ 0.   1.   0.   0. ]
 [ 0.2  0.8  0.4  0.4]]


### 1.5 - Broadcasting and the softmax function
### - np.sum(value, axis=int, keepdims=bool)

In [146]:
# GRADED FUNCTION: softmax

def softmax(x):
    """Calculates the softmax for each row of the input x.
    Your code should work for a row vector and also for matrices of shape (n, m).
    Argument:    x -- A numpy matrix of shape (n,m)
    Returns:    s -- A numpy matrix equal to the softmax of x, of shape (n,m)
    """
    
    x_exp = np.exp(x)
    x_sum = np.sum(x_exp, axis = 1, keepdims = True)
    s = x_exp / x_sum
    print(" ")
    print("X_EXP")
    print(x_exp)
    print(" ")
    print("X_SUM")
    print(x_sum)
    print(" ")
    print("SOFTMAX")
    return s

x = np.array([
    [1, 1, 1],
    [2, 3, 2]])





print(str(softmax(x)))

 
X_EXP
[[  2.71828183   2.71828183   2.71828183]
 [  7.3890561   20.08553692   7.3890561 ]]
 
X_SUM
[[  8.15484549]
 [ 34.86364912]]
 
SOFTMAX
[[ 0.33333333  0.33333333  0.33333333]
 [ 0.21194156  0.57611688  0.21194156]]


## 2) Vectorization
### - import time
### - time.process_time()
### - np.zeros(x,y)
### - np.dot(x,y)
### - np.outer(x,y)
### - np.multiply(x,y)
### - np.random.rand(x,y)

In [248]:
import time

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot+= x1[i]*x2[i]
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC OUTER PRODUCT IMPLEMENTATION ###
tic = time.process_time()
outer = np.zeros((len(x1),len(x2))) # we create a len(x1)*len(x2) matrix with only zeros
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i]*x2[j]
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC ELEMENTWISE IMPLEMENTATION ###
tic = time.process_time()
mul = np.zeros(len(x1))
for i in range(len(x1)):
    mul[i] = x1[i]*x2[i]
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC GENERAL DOT PRODUCT IMPLEMENTATION ###
W = np.random.rand(3,len(x1)) # Random 3*len(x1) numpy array
tic = time.process_time()
gdot = np.zeros(W.shape[0])
for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i,j]*x1[j]

        toc = time.process_time()
print ("gdot = " + str(gdot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

dot = 278
 ----- Computation time = 0.14642500000050518ms
outer = [[ 81.  18.  18.  81.   0.  81.  18.  45.   0.   0.  81.  18.  45.   0.
    0.]
 [ 18.   4.   4.  18.   0.  18.   4.  10.   0.   0.  18.   4.  10.   0.
    0.]
 [ 45.  10.  10.  45.   0.  45.  10.  25.   0.   0.  45.  10.  25.   0.
    0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.]
 [ 63.  14.  14.  63.   0.  63.  14.  35.   0.   0.  63.  14.  35.   0.
    0.]
 [ 45.  10.  10.  45.   0.  45.  10.  25.   0.   0.  45.  10.  25.   0.
    0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.]
 [ 81.  18.  18.  81.   0.  81.  18.  45.   0.   0.  81.  18.  45.   0.
    0.]
 [ 18.   4.   4.  18.   0.  18.   4.  10.   0.   0.  1

In [257]:
print("NP.ZEROS")

zy = [1,2,3]
yy = [4,5,6]
xyz = np.zeros((len(zy),len(yy))) # we create a len(x1)*len(x2) matrix with only zeros
print(xyz)

NP.ZEROS
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [253]:
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### VECTORIZED DOT PRODUCT OF VECTORS ###
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED OUTER PRODUCT ###
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED ELEMENTWISE MULTIPLICATION ###
tic = time.process_time()
mul = np.multiply(x1,x2) 
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED GENERAL DOT PRODUCT ###
tic = time.process_time()
dot = np.dot(W,x1)
toc = time.process_time()
print ("gdot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")


dot = 278
 ----- Computation time = 0.1478390000002605ms
outer = [[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [63 14 14 63  0 63 14 35  0  0 63 14 35  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
 ----- Computation time = 0.15795899999915264ms
elementwise multiplication = [81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]
 ----- Computation time = 0.20974799999962102ms
gdot = [ 16.30886224  20.67899031  18.5073

### NP.DOT

dodaje w pionowej osi pary przemnozonych przez siebie xy[1] i xr[1] i po kolei dalej

In [318]:
xr = [1,2,3]
yr = [10,10,20]
xyrdot = np.dot(xr,yr)
print(xyrdot)

90


### NP.MULTIPLY(x,y)

mnoży w pionowej osi przez siebie pary ale nie sumuje ich

In [319]:
xr = [1,2,3]
yr = [10,10,20]
xyrmul = np.multiply(xr,yr)
print(xyrmul)

[10 20 60]


### NP.OUTER

tworzy matrix niemal jak tabele o bokach xr pion i yr poziom

In [323]:
xr = [1,2,3] #PION
yr = [10,10,20] #POZIOM
xyrouter = np.outer(xr,yr)
print(xyrouter)

[[10 10 20]
 [20 20 40]
 [30 30 60]]


### 2.1 Implement the L1 and L2 loss functions
### - np.absolute()

In [326]:
# GRADED FUNCTION: L1

def L1(yhat, y):
    """
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    loss -- the value of the L1 loss function defined above
    """
    loss = np.sum(np.absolute(yhat-y), axis=0, keepdims=True)
    return loss

yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat,y)))

L1 = [ 1.1]


In [330]:
# GRADED FUNCTION: L2

def L2(yhat, y):
    loss = np.sum(np.absolute(yhat-y)**2, axis=0, keepdims=True)
    return loss

yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L2 = " + str(L2(yhat,y)))

L2 = [ 0.43]


In [341]:
# np.ABSOLUTE / np.abs

xnoabs = 323
xabs = np.absolute(323.2323 / 323.2334)
xheh = 323.23 / 323.2334
print(xabs)
print(xheh)

0.999996596886
0.9999894812850405


In [357]:
# np.RANDOM.RAND

xrand = np.random.rand(2,3,4)
print(xrand)

[[[ 0.34322454  0.83182304  0.78201277  0.44701588]
  [ 0.85951498  0.59133266  0.65097986  0.74957027]
  [ 0.56099697  0.15232241  0.15680674  0.73974774]]

 [[ 0.86333563  0.31746296  0.68956043  0.11711711]
  [ 0.90667781  0.73509781  0.17372047  0.08527577]
  [ 0.63374954  0.08984535  0.94349541  0.11455304]]]


In [376]:
yrand = np.random.rand(10-5,3+2)
print(yrand)

[[ 0.05311245  0.63841058  0.2077077   0.58723022  0.38911338]
 [ 0.38722534  0.14077834  0.42191402  0.35692057  0.43432944]
 [ 0.54352303  0.11645814  0.00309079  0.79094861  0.71162362]
 [ 0.47863862  0.71807807  0.53252313  0.45249045  0.88266422]
 [ 0.51042684  0.29902699  0.86093758  0.55885854  0.45267454]]


### np.squeeze()  i inne
Remove single-dimensional entries from the shape of an array.
The input array, but with all or a subset of the dimensions of length 1 removed. 
This is always a itself or a view into a.


In [378]:
x = np.array([[[0], [1], [2]]])
print(x)
y = x.shape
print(y)
z = np.squeeze(x).shape
print(z)
f = np.squeeze(x, axis=(2,)).shape
print(f)

[[[0]
  [1]
  [2]]]
(1, 3, 1)
(3,)
(1, 3)


In [ ]:
np.log() #Liczy logarytm

In [ ]:
np.mean() # Średnia https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.mean.html

In [ ]:
np.tanh() # Wykres tanh

In [ ]:
np.round() # no pewnie zaokragla ;d

In [ ]:
np.random.seed() # ?

In [ ]:
np.random.randn # inny random